// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeTtPaW9trJ6Xcmn5BL25CkCVv8bI0BGg',
    appId: '1:669654098015:web:04c0b296b53acd0fc03bea',
    messagingSenderId: '669654098015',
    projectId: 'whitefihes',
    authDomain: 'whitefihes.firebaseapp.com',
    storageBucket: 'whitefihes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMCmkJFfszU91YEFn-xWxFVHXH3Eggv5A',
    appId: '1:669654098015:android:61fe29d50ec72cc3c03bea',
    messagingSenderId: '669654098015',
    projectId: 'whitefihes',
    storageBucket: 'whitefihes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa4kJsOUJ9Q_QCRr6HzhG0Rfzf3jwmO_o',
    appId: '1:669654098015:ios:f04f6c84dee450ecc03bea',
    messagingSenderId: '669654098015',
    projectId: 'whitefihes',
    storageBucket: 'whitefihes.appspot.com',
    iosBundleId: 'com.example.whiteFishes2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa4kJsOUJ9Q_QCRr6HzhG0Rfzf3jwmO_o',
    appId: '1:669654098015:ios:f04f6c84dee450ecc03bea',
    messagingSenderId: '669654098015',
    projectId: 'whitefihes',
    storageBucket: 'whitefihes.appspot.com',
    iosBundleId: 'com.example.whiteFishes2',
  );
}
